name: scmodal
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anndata=0.8.0
  - aom=3.5.0
  - blas=2.137
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2024.8.30
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - cycler=0.11.0
  - dav1d=1.2.1
  - ffmpeg=6.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.14
  - h5py=3.7.0
  - harfbuzz=7.3.0
  - hdf5=1.12.2
  - icu=72.1
  - idna=3.10
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - joblib=1.3.2
  - jpeg=9e
  - keyutils=1.6.3
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.16.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.14
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.0
  - libgomp=15.2.0
  - libhwloc=2.9.3
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libva=2.18.0
  - libvpx=1.13.1
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - llvmlite=0.39.1
  - matplotlib-base=3.5.3
  - mkl=2024.2.2
  - mkl-devel=2024.2.2
  - mkl-include=2024.2.2
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=2.7
  - numba=0.56.3
  - numpy=1.21.6
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.5.4
  - p11-kit=0.24.1
  - packaging=23.2
  - pandas=1.3.5
  - patsy=0.5.6
  - pcre2=10.46
  - pillow=9.2.0
  - pip=24.0
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pynndescent=0.5.13
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.9.0
  - python_abi=3.7
  - pytorch=1.13.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.2
  - readline=8.2
  - requests=2.32.2
  - scanpy=1.9.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - session-info=1.0.0
  - setuptools=59.8.0
  - six=1.16.0
  - sqlite=3.50.4
  - statsmodels=0.13.2
  - stdlib-list=0.11.0
  - svt-av1=1.6.0
  - tbb=2021.11.0
  - threadpoolctl=3.1.0
  - tk=8.6.13
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.67.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - umap-learn=0.5.3
  - unicodedata2=14.0.0
  - urllib3=2.2.1
  - wheel=0.42.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zipp=3.15.0
  - zlib=1.3.1
  - zstd=1.5.7
