name: scvi-gpu-cuda11.8
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cpython=3.10.16
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Specify CUDA version
  - gmp=6.3.0
  - gmpy2=2.1.5
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openssl=3.4.0
  - pip=25.0
  - python=3.10.16
  - python_abi=3.10
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=75.8.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - yaml=0.2.5
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.1
      - anndata==0.11.1
      - array-api-compat==1.9.1
      - async-timeout==5.0.1
      - attrs==25.1.0
      - build==1.0.3
      - cachecontrol==0.13.1
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - chex==0.1.87
      - clarabel==0.9.0
      - cleo==2.1.0
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - crashtest==0.4.1
      - cryptography==44.0.0
      - cvxpy==1.6.0
      - cycler==0.12.1
      - decorator==4.4.2
      - distlib==0.3.8
      - docrep==0.3.2
      - dulwich==0.21.7
      - etils==1.11.0
      - exceptiongroup==1.2.2
      - fastjsonschema==2.19.1
      - filelock==3.16.1
      - flatbuffers==23.5.26
      - flax==0.10.2
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - get-annotations==0.1.2
      - grpcio==1.68.1
      - h5py==3.12.1
      - humanfriendly==10.0
      - humanize==4.11.0
      - idna==3.4
      - igraph==0.11.8
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.1
      - importlib-resources==6.4.5
      - installer==0.7.0
      - jaraco-classes==3.3.1
      - jax==0.4.37
      - jaxlib==0.4.36 # Consider jaxlib with CUDA if available and needed
      - jeepney==0.8.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - keyring==24.3.0
      - kiwisolver==1.4.7
      - lazy-loader==0.3
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - llvmlite==0.43.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.5.0
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - numba==0.60.0
      - numpy==1.26.4
      - numpyro==0.16.1
      - onnxruntime==1.17.0 # Consider onnxruntime-gpu if needed
      - opencv-python-headless==4.9.0.80
      - opentsne==1.0.2
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.10.2
      - osqp==0.6.7.post3
      - packaging==24.2
      - pandas==2.2.3
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==10.2.0
      - pkginfo==1.9.6
      - platformdirs==3.11.0
      - plotly==5.24.1
      - poetry==1.7.1
      - poetry-core==1.8.1
      - poetry-plugin-export==1.6.0
      - pooch==1.8.0
      - pot==0.9.5
      - proglog==0.1.10
      - propcache==0.2.1
      - protobuf==5.29.1
      - ptyprocess==0.7.0
      - py-pcha==0.1.3
      - pycparser==2.22
      - pygments==2.19.1
      - pymatting==1.1.12
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - pypdf2==3.0.1
      - pyproject-hooks==1.0.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      # - python-graphviz==0.20.3
      - pytorch-lightning==2.4.0
      - pytz==2025.1
      - qdldl==0.1.7.post4
      - rapidfuzz==3.6.1
      - referencing==0.33.0
      - rembg==2.0.54
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.17.1
      - scanpy==1.10.4
      - scikit-image==0.22.0
      - scikit-learn==1.6.0
      - scikit-misc==0.5.1
      - scipy==1.12.0
      - scs==3.2.7
      - scvi-tools==1.2.2.post2
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - session-info==1.0.0
      - shellingham==1.5.4
      - simplejson==3.19.3
      - six==1.17.0
      - sparse==0.15.4
      - statsmodels==0.14.4
      - stdlib-list==0.11.0
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.69
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.1.30
      - tomli==2.0.1
      - tomlkit==0.12.3
      - toolz==1.0.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - tabulate==0.9.0
      - trove-classifiers==2024.1.31
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==1.26.13
      - virtualenv==20.25.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - xarray==2024.11.0
      - xlrd==2.0.1
      - yarl==1.18.3
      - zipp==3.21.0
