name: maxfuse
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - ld_impl_linux-64=2.44
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=24.3.1
  - python=3.8.20
  - readline=8.2
  - setuptools=75.3.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstd=1.5.7
  - pip:
      - alembic==1.14.1
      - anndata==0.9.2
      - asttokens==3.0.0
      - backcall==0.2.0
      - blinker==1.8.2
      - cachetools==5.5.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - databricks-sdk==0.70.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - deprecated==1.2.18
      - docker==7.1.0
      - executing==2.2.1
      - flask==3.0.3
      - fonttools==4.57.0
      - get-annotations==0.1.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - gunicorn==23.0.0
      - h5py==3.11.0
      - idna==3.11
      - igraph==0.11.8
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - leidenalg==0.10.2
      - llvmlite==0.41.1
      - mako==1.3.10
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - maxfuse==0.0.2
      - mlflow==2.17.2
      - mlflow-skinny==2.17.2
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.4
      - opentelemetry-api==1.33.1
      - opentelemetry-sdk==1.33.1
      - opentelemetry-semantic-conventions==0.54b1
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.5
      - patsy==1.0.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydot==4.0.1
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - requests==2.32.4
      - rsa==4.9.1
      - scanpy==1.9.8
      - scib==1.1.5
      - scikit-learn==1.3.2
      - scikit-misc==0.2.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - session-info==1.0.1
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - torchaudio==2.0.2+cpu
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==2.2.3
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - wrapt==1.17.3
      - zipp==3.20.2
