name: scvi
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=25.3.0
  - beautifulsoup4=4.14.2
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cpython=3.10.16
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.55
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - defusedxml=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libedit=3.1.20250104
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.4
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markdown-it-py=4.0.0
  - markupsafe=2.1.5
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - mistune=3.1.4
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openssl=3.5.3
  - pandoc=3.8.1
  - pandocfilters=1.5.0
  - pip=25.0
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyzmq=27.1.0
  - readline=8.2
  - referencing=0.36.2
  - rpds-py=0.27.1
  - setuptools=75.8.0
  - six=1.17.0
  - soupsieve=2.8
  - sympy=1.13.3
  - tbb=2021.13.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - webencodings=0.5.1
  - wheel=0.45.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.1
      - alembic==1.16.1
      - anndata==0.11.1
      - annotated-types==0.7.0
      - ansicolors==1.1.8
      - anyio==4.9.0
      - array-api-compat==1.9.1
      - async-timeout==5.0.1
      - blessed==1.22.0
      - blinker==1.9.0
      - bokeh==3.8.0
      - build==1.0.3
      - cachecontrol==0.13.1
      - cachetools==5.5.2
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - chex==0.1.87
      - clarabel==0.9.0
      - cleo==2.1.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - crashtest==0.4.1
      - cryptography==44.0.0
      - cvxpy==1.6.0
      - cycler==0.12.1
      - dask==2024.11.2
      - databricks-sdk==0.57.0
      - decorator==4.4.2
      - distlib==0.3.8
      - distributed==2024.11.2
      - docker==7.1.0
      - docrep==0.3.2
      - dulwich==0.21.7
      - etils==1.11.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - filelock==3.16.1
      - flask==3.0.3
      - flatbuffers==23.5.26
      - flax==0.10.2
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2023.6.0
      - gensim==4.3.3
      - get-annotations==0.1.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - gpustat==1.1.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - graphviz==0.20.3
      - greenlet==3.2.3
      - grpcio==1.68.1
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.12.1
      - httpcore==1.0.9
      - humanfriendly==10.0
      - humanize==4.11.0
      - idna==3.4
      - igraph==0.11.8
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.1
      - importlib-resources==6.4.5
      - installer==0.7.0
      - itsdangerous==2.2.0
      - jaraco-classes==3.3.1
      - jax==0.4.37
      - jaxlib==0.4.36
      - jeepney==0.8.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - jupyterlab==4.4.7
      - jupytext==1.17.2
      - keyring==24.3.0
      - kiwisolver==1.4.7
      - lazy-loader==0.3
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - llvmlite==0.43.0
      - lz4==4.4.4
      - mako==1.3.10
      - markdown==3.7
      - matplotlib==3.9.2
      - ml-collections==1.0.0
      - ml-dtypes==0.5.0
      - mlflow==3.1.0
      - mlflow-skinny==3.1.0
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - narwhals==2.5.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - node2vec==0.5.0
      - notebook==7.4.5
      - numba==0.60.0
      - numpy==1.26.4
      - numpyro==0.16.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - onnxruntime==1.17.0
      - opencv-python-headless==4.9.0.80
      - opentelemetry-api==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - opentsne==1.0.2
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.10.2
      - osqp==0.6.7.post3
      - packaging==24.2
      - pandas==2.2.3
      - papermill==2.6.0
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==10.2.0
      - pkginfo==1.9.6
      - platformdirs==3.11.0
      - plotly==5.24.1
      - poetry==1.7.1
      - poetry-core==1.8.1
      - poetry-plugin-export==1.6.0
      - pooch==1.8.0
      - pot==0.9.5
      - proglog==0.1.10
      - propcache==0.2.1
      - protobuf==5.29.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - py-pcha==0.1.3
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pymatting==1.1.12
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - pypdf2==3.0.1
      - pyproject-hooks==1.0.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytorch-lightning==2.4.0
      - pytz==2025.1
      - pyyaml==6.0.3
      - qdldl==0.1.7.post4
      - rapidfuzz==3.6.1
      - rembg==2.0.54
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rsa==4.9.1
      - scanpy==1.10.4
      - scikit-image==0.22.0
      - scikit-learn==1.6.0
      - scikit-misc==0.5.1
      - scipy==1.12.0
      - scs==3.2.7
      - scvi-tools==1.2.2.post2
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - session-info==1.0.0
      - shellingham==1.5.4
      - simplejson==3.19.3
      - smart-open==7.3.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sparse==0.15.4
      - sqlalchemy==2.0.41
      - sqlparse==0.5.3
      - starlette==0.46.2
      - statsmodels==0.14.4
      - stdlib-list==0.11.0
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.69
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.1.30
      - tomlkit==0.12.3
      - toolz==1.0.0
      - torch==2.2.0+cu121
      - torchaudio==2.2.0+cu121
      - torchmetrics==1.8.2
      - torchvision==0.17.0+cu121
      - tqdm==4.67.1
      - tabulate==0.9.0
      - triton==2.2.0
      - trove-classifiers==2024.1.31
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==1.26.13
      - uvicorn==0.34.3
      - virtualenv==20.25.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - xarray==2024.11.0
      - xlrd==2.0.1
      - xyzservices==2025.4.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /home/barroz/.conda/envs/scvi
